name: run-pytest-tests

on:
  workflow_run:
    workflows: [empty-workflow]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest tests/

    - name: Check if secrets are accessible
      run: |
          echo "Repository Event Full Name: ${{ github.event.repository.full_name }}"
          echo "Repository Name: ${{ github.repository }}"
          echo "Is Fork: ${{ github.event.repository.fork }}"
          if [[ "x${{ secrets.MY_SECRET }}" == "xval" ]]; then
            echo "Access to secrets"
          else
            echo "No access to secrets"
            exit 1
          fi
