name: empty-workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print GITHUB_WORKSPACE
        run: |
            echo ${GITHUB_WORKSPACE}
            pwd
            ls -lah
